/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const TablesLazyImport = createFileRoute('/tables')()
const QueryLazyImport = createFileRoute('/query')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const TablesLazyRoute = TablesLazyImport.update({
  path: '/tables',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/tables.lazy').then((d) => d.Route))

const QueryLazyRoute = QueryLazyImport.update({
  path: '/query',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/query.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/query': {
      id: '/query'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof QueryLazyImport
      parentRoute: typeof rootRoute
    }
    '/tables': {
      id: '/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  QueryLazyRoute,
  TablesLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/query",
        "/tables"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/query": {
      "filePath": "query.lazy.tsx"
    },
    "/tables": {
      "filePath": "tables.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
