// Auto-generated by @farming-labs/next — do not edit manually.

import { createDocsAPI } from "@farming-labs/theme/api";

export const { GET, POST } = createDocsAPI();

export const revalidate = false;
