import type { editor } from "monaco-editor";

export const lightThemeData: editor.IStandaloneThemeData = {
  base: "vs",
  inherit: true,
  rules: [
    { token: "binary.sql", foreground: "45AB5A" },
    { token: "binary.escape.sql", foreground: "45AB5A" },
    { token: "number.sql", foreground: "45AB5A" },
    { token: "number.float.sql", foreground: "45AB5A" },
    { token: "number.binary.sql", foreground: "45AB5A" },
    { token: "number.octal.sql", foreground: "45AB5A" },
    { token: "number.hex.sql", foreground: "45AB5A" },
    { token: "comment.sql", foreground: "B1B4C5" },
    { token: "comment.quote.sql", foreground: "B1B4C5" },
    { token: "delimiter.sql", foreground: "7D98B1" },
    { token: "operator.sql", foreground: "7D98B1" },
    { token: "operator.symbol.sql", foreground: "7D98B1" },
    { token: "delimiter.curly.sql", foreground: "B1BB86" },
    { token: "delimiter.paren.sql", foreground: "B1BB86" },
    { token: "delimiter.square.sql", foreground: "B1BB86" },
    { token: "identifier.sql", foreground: "201A1A" },
    { token: "identifier.quote.sql", foreground: "201A1A" },
    { token: "keyword.sql", foreground: "3300FF" },
    { token: "operator.keyword.sql", foreground: "3300FF" },
    { token: "keyword.scope.sql", foreground: "E221DA" },
    { token: "predefined.sql", foreground: "C3771C" },
    { token: "string.sql", foreground: "BC1313" },
    { token: "string.escape.sql", foreground: "BC1313" },
    { token: "type.sql", foreground: "256FC6" },
    { token: "variable.sql", foreground: "00AD84" },
  ],
  colors: {},
};

export const darkThemeData: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "binary.sql", foreground: "b5cea8" },
    { token: "binary.escape.sql", foreground: "b5cea8" },
    { token: "comment.sql", foreground: "6a9955" },
    { token: "comment.quote.sql", foreground: "6a9955" },
    { token: "delimiter.sql", foreground: "d4d4d4" },
    { token: "delimiter.curly.sql", foreground: "da70d6" },
    { token: "delimiter.paren.sql", foreground: "ffd700" },
    { token: "delimiter.square.sql", foreground: "ffd700" },
    { token: "identifier.sql", foreground: "9cdcfe" },
    { token: "identifier.quote.sql", foreground: "9cdcfe" },
    { token: "keyword.sql", foreground: "569cd6" },
    { token: "keyword.scope.sql", foreground: "c586c0" },
    { token: "number.sql", foreground: "b5cea8" },
    { token: "number.float.sql", foreground: "b5cea8" },
    { token: "number.binary.sql", foreground: "b5cea8" },
    { token: "number.octal.sql", foreground: "b5cea8" },
    { token: "number.hex.sql", foreground: "b5cea8" },
    { token: "operator.sql", foreground: "d4d4d4" },
    { token: "operator.keyword.sql", foreground: "569cd6" },
    { token: "operator.symbol.sql", foreground: "d4d4d4" },
    { token: "predefined.sql", foreground: "dcdcaa" },
    { token: "string.sql", foreground: "ce9178" },
    { token: "string.escape.sql", foreground: "ce9178" },
    { token: "type.sql", foreground: "4ec9b0" },
    { token: "variable.sql", foreground: "4fc1ff" },
  ],
  colors: {},
};
